baseURL = "https://nicosvg.github.io/site-cse-labs"
languageCode = "fr-fr"
title = "CSE Talan Labs"
theme = "blist"
canonifyURLs = true

DefaultContentLanguage = "fr"
DefaultContentLanguageInSubdir = true
[languages]
    [languages.fr]
        contentDir = "content/fr" #French
        weight = 1
        languageName = "Français"
    [languages.fr.params]
        introTitle = "Bienvenue sur le site du CSE Talan Labs"
        introSubtitle = "... en cours de construction"
        introPhoto = "./logo-cse-color.jpg"
    [[languages.fr.menu.main]]
        name = "Blog"
        url = "blog"
        weight = 1
    [[languages.fr.menu.main]]
        name = "About"
        url = "page/about/"
        weight = 2
    [[languages.fr.menu.main]]
        name = "Tags"
        url = "tags"
        weight = 3

[params]
    # Enable the darkmode toggle in header
    darkModeToggle = true

    # Enable search in header
    enableSearch = true

    # Custom copyright - optional
    copyright = "Copyright © 2021 - CSE Talan Labs · All rights reserved"
    favicon = "/favicon.svg"

    # Color for the intro details and social links block, not applicable for dark mode
    # Supported values: Any color from TailwindCSS default colors
    # Reference: https://tailwindcss.com/docs/customizing-colors
    ascentColor = "bg-blue-100"